### ISSUE TITLE
Does auctions.data corrupt because the new data is not completely overwriting the old?

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#63]
Everything looked good one second earlier.

I canceled an auction and now the data has an invalid entry.

It looks like the entry is removed just fine, BUT the list of entries is shorter, and now there's the "leftover" bit at the end.

Example:

**You have the alphabet:** abcdefghijklmnopqrstuvwxyz

**Remove vowels and save over previous data:** 

**Result using an inference based on observations:** bcdfghjklmnpqrstvwxzuvwxyz

**Add back the vowels:**
abcdefghijklmnopqrstuvwxyzuvwxyz

etc...

There's data at the end which accumulates.

Data below is after canceling one auction. Notice that the seemingly duplicated data is about one whole entry in length, but a bit less.

```
'5051':
  ==: com.robomwm.gpauctions.auction.Auction
  owner: 34ad6d8f-969e-4a78-98b5-68c8149b0234
  startingBid: 39600.0
  bids: []
  signLocation:
    ==: org.bukkit.Location
    world: world
    x: 1846.0
    y: 67.0
    z: -12.0
    pitch: 0.0
    yaw: 0.0
  claimID: 5051
  endTime: 1571728547473

051':
  ==: com.robomwm.gpauctions.auction.Auction
  owner: 34ad6d8f-969e-4a78-98b5-68c8149b0234
  startingBid: 39600.0
  bids: []
  signLocation:
    ==: org.bukkit.Location
    world: world
    x: 1846.0
    y: 67.0
    z: -12.0
    pitch: 0.0
    yaw: 0.0
  claimID: 5051
  endTime: 1571728547473
```
